name: flutter_application
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6


  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_calendar_carousel: ^2.0.0
  jiffy: ^6.2.1 # Replace with the desired version
  table_calendar: ^3.0.1 # Replace with the desired version
  provider: ^6.0.5
  webview_flutter: ^2.0.13
  carousel_slider: ^4.0.0
  flutter_lints: ^2.0.3  # Update the version to 2.0.3
  url_launcher: ^6.0.5 # Or the appropriate version
  flutter_screenutil: ^5.0.0 # Use the latest version or specify a version range
  image_picker: ^0.8.9
  convex_bottom_bar: ^3.2.0
  #draggable_widget: ^2.0.0
  #arcore_flutter_plugin: ^0.1.0
  #ar_flutter_plugin: ^0.7.3

 # ar_flutter_plugin: ^0.7.3
 # easy_camera_plus: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  #arkit_plugin: ^1.0.7
  http: ^1.1.0
  cupertino_icons: ^1.0.2  # Add Cupertino icons if not already included 

flutter:
  uses-material-design: true
  assets:
    - images/monasaba.png
    - images/download.png
    - images/999.jpg
    - images/2.png
    - images/33.png
    - images/rings.png
    - images/graduation.png
    - images/baby-shower.png
    - images/happy-birthday.png
    - images/1.avif
    - images/blank-profile-circle.png
    - images/w.jpeg
    - images/ت.jpeg
    - images/s.jpeg
    - images/s1.jpeg
    - images/1_white.jpeg
    - images/2_white.jpeg
    - images/3_white.jpeg
    - images/4_white.jpeg
    - images/1_pink.jpeg
    - images/2_pink.jpeg
    - images/3_pink.jpeg
    - images/4_pink.jpeg
    - images/5_pink.jpeg
    - images/6_pink.jpeg
    - images/1_red.jpeg
    - images/2_red.jpeg
    - images/3_red.jpeg
    - images/4_red.jpeg
    - images/5_red.jpeg
    - images/6_red.jpeg
    - images/1_green.jpeg
    - images/2_green.jpeg
    - images/3_green.jpeg
    - images/4_green.jpeg
    - images/5_green.jpeg
    - images/1_other.jpeg
    - images/2_other.jpeg
    - images/3_other.jpeg
    - images/4_other.jpeg
    - images/5_other.jpeg
    - images/6_other.jpeg
    - images/7_other.jpeg
    - images/8_other.jpeg
    - images/9_other.jpeg
    - images/10_other.jpeg
    - images/facebook.png
    - images/instagram.png
    - images/ج.jpeg
    - images/golden.jpeg
    - images/1w_white.jpeg
    - images/2w_white.jpeg
    - images/3w_white.jpeg
    - images/4w_white.jpeg
    - images/5w_white.jpeg
    - images/6w_white.jpeg
    - images/7w_white.jpeg
    - images/8w_white.jpeg
    - images/1c_other.jpeg
    - images/2c_other.jpeg
    - images/3c_other.jpeg
    - images/4c_other.jpeg
    - images/5c_other.jpeg
    - images/6c_other.jpeg
    - images/7c_other.jpeg
    - images/8c_other.jpeg
    - images/1g_gold.jpeg
    - images/2g_gold.jpeg
    - images/3g_gold.jpeg
    - images/4g_gold.jpeg
    - images/5g_gold.jpeg
    - images/1b_black.jpeg
    - images/2b_black.jpeg
    - images/3b_black.jpeg
    - images/4b_black.jpeg
    - images/5b_black.jpeg
    - images/6b_black.jpeg
    - images/11_white.jpg
    - images/22_white.jpg
    - images/33_white.jpg
    - images/44_white.jpg
    - images/11_pink.jpg
    - images/22_pink.jpg
    - images/33_pink.jpg
    - images/44_pink.jpg
    - images/55_pink.jpg
    - images/11_green.jpg
    - images/22_green.jpg
    - images/33_green.jpg
    - images/44_green.jpg
    - images/11_other.jpg
    - images/22_other.jpg
    - images/33_other.jpg
    - images/44_other.jpg
    - images/1s_pink.jpg
    - images/2s_pink.jpg
    - images/3s_pink.jpg
    - images/4s_pink.jpg
    - images/1s_green.jpg
    - images/2s_green.jpg
    - images/3s_green.jpg
    - images/4s_green.jpg
    - images/welcome1.jpg
    - images/welcome2.jpg
    - images/welcome3.jpg
    - images/normal_pink.jpeg
    - images/natural_white.jpeg
    - images/