name: flutter_application
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  font_awesome_flutter: 10.6.0
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_calendar_carousel: ^2.0.0
  jiffy: ^6.2.1 # Replace with the desired version
  table_calendar: ^3.0.1 # Replace with the desired version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - images/monasaba.png
    - images/download.png
